- name: Initial server configuration
  hosts: all
  become: yes
  tasks:
    - name: Create ansible-worker user
      ansible.builtin.user:
        name: ansible-worker
        state: present
        shell: /bin/bash
        groups: www-data
      tags: user
    - name: Group setting for ansible-worker
      ansible.builtin.file:
        path: "/home/ansible-worker"
        owner: www-data
        group: ansible-worker
      tags: user
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
      tags:
        - git
    - name: Copy private SSH key
      ansible.builtin.copy:
        src: "./ssh_keys/id_rsa"
        dest: "~/.ssh/id_rsa"
        mode: '0600'
      tags:
        - git
    - name: Copy public SSH key
      ansible.builtin.copy:
        src: "./ssh_keys/id_rsa.pub"
        dest: "~/.ssh/id_rsa.pub"
        mode: '0644'
      tags:
        - git
    - name: Clone repository
      ansible.builtin.git:
        repo: "https://github.com/iphilka/stud-template.git"
        dest: "/home/ansible-worker/www/stud-template"
        clone: yes
        update: no
      tags: clone
    - name: Copy index.html file
      ansible.builtin.copy:
        src: "./files/index.html"
        dest: "/home/ansible-worker/www/stud-template/index.html"
        mode: '0644'
      tags: nginx

    - name: Set for www-data group
      ansible.builtin.file:
        path: "/home/ansible-worker/www"
        owner: www-data
        group: ansible-worker
        mode: "0755"
        recurse: yes
      tags: nginx
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      tags:
        - nginx
    - name: Create Nginx configuration file
      ansible.builtin.template:
        src: "./files/ansible.iphilka.ru.conf"
        dest: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
      notify: Restart Nginx
      tags: nginx
    - name: Enable Nginx site
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
        dest: "/etc/nginx/sites-enabled/ansible.iphilka.ru.conf"
        state: link
      tags: nginx
    - name: Copy index.html file ### Если это не нужно, то прошу прощения, думал это нужно для практической хоть этого и не написано.
      ansible.builtin.copy:
        src: "./files/index.html"
        dest: "/var/www/html/index.html"
        mode: '0644'
      tags: dop
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: reloaded